- name: This sets up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/ap-south.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
  - name: "Install httpd and php packages"
    package:
        name:
          - "httpd"
          - "php"
        state: present
  - name: "copy code from GitHub"
    copy:
        src: 
          - "/etc/ansible/index.html"
          - "/etc/ansible/error.html"
          - "/etc/ansible/profile.jpg"
        dest: "/var/www/html/"
        force: yes
  - name: "Start httpd services"
    service:
        name: httpd
        state: started
  - name: Yum Install Packages
    yum: name={{item}} state=latest
    with_items:
       - wget
  - name: terraform install
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
      
